version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: pg_database2
    restart: no
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_secret_password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - pg_data2:/var/lib/postgresql/data

volumes:
  pg_data2:
